### ISSUE TITLE
CONSENSUS FAILURE on the first deposit

### ISSUE THREAD

**Issue by troggy** [leapdao/integration-tests#18]
Failed on the deposit in `1_depositTransferExit.js`

Flacky bug. Multiple validators are not working right.

Logs: https://gist.github.com/troggy/37a79cf929f5eb17238018dc59ac736d

**Comment by johannbarbie** [comment]
mh, what i see is:
- 3 validators were running
- 1 didn't catch the epoch-length event on time
- epochLength transactions was rejected

wouldn't the delays configured on testnet and mainnet prevent that?

**Comment by troggy** [comment]
right, integration tests are running without properly configured event buffers. good catch
