### ISSUE TITLE
allow to use integration tests as local development environment with different recipes

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/integration-tests#37]
# Bounty

instead of running the tests, and then stopping the nodes, rather run a single recipe, and keep the nodes on.

## Scope
- remove exit at the end
- create a folder with recipes
- allow to pick a recipe and start the environment

## Deliverables
- code
- docker wrapper

## Gain for the project
- local development environment

## Roles
prototyping gardener: @johann / 45%
passionate worker: name / 35%
dockerizing reviewer: @pinkiebell  / 20%

**Comment by johannbarbie** [comment]
work started here: https://github.com/leapdao/integration-tests/pull/36

**Comment by troggy** [comment]
via #36
