### ISSUE TITLE
Create a test resyncing the testnet once a day

### ISSUE THREAD

**Issue by troggy** [leapdao/integration-tests#54]
# Bounty

To prevent bugs like https://github.com/leapdao/leap-node/issues/324, we want to be sure that latest changes to the node and contracts (ABI) are backward compatible.

## Scope
- create a separate script which starts the latest leap-node using [testnet config](https://github.com/leapdao/leap-node/blob/master/presets/leap-testnet.json)
- the script should start the node in a background on a remote EC2 instance
- schedule the script to run once a day. Skip the run if there were no changes in `master` branch (use `git pull` for faster builds)
- schedule a job to check the sync status (e.g. a cronjob on the same EC2). Once finished or failed, post the status to the Slack #development channel

## Worker deliverables
- [x] script to start the node
- [x] script to check the status and post to slack
- [x] both scripts set up on the EC2 and tested

## Reviewer checklist
- [ ] review the code for logical correctness, inefficiencies and style (TBD)
- [ ] ensure the script is using the right env (network and code)
- [ ] ensure the script is posting status to the slack
- [ ] try the script with a failing configuration, it should fail and post to Slack
- [ ] try the script with a working configuration, it should pass and post to Slack

## Gain for the project
peace of mind for testnet and mainnet commanders

## Roles
bounty gardener: @troggy / 70 DAI flat
bounty worker: @troggy / 85% / 224 DAI
bounty reviewer: name / 20% / 56 DAI

**Comment by troggy** [comment]
@johannbarbie 2 months later do you think it is still needed?

**Comment by johannbarbie** [comment]
yeah, we would have found the current syncing issue with the testnet earlier :)
